# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-23 06:04
from __future__ import unicode_literals

import disturbance.components.compliances.models
import disturbance.components.proposals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0017_auto_20191030_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalApiaryDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('_file', models.FileField(max_length=512, upload_to=disturbance.components.proposals.models.update_apiary_doc_filename)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiary_documents', to='disturbance.Proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalApiarySiteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_site_location', to='disturbance.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalApiarySiteTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email of Transferee')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_site_transfer', to='disturbance.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalApiaryTemporaryUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Period From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Period To Date')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_temporary_use', to='disturbance.Proposal')),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Apiary', 'Apiary')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
