# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-26 07:56
from __future__ import unicode_literals

import disturbance.components.compliances.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0018_auto_20200423_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiarysitelocation',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
