# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-26 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_auto_20250226_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='label',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
