# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-26 08:11
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0019_auto_20200426_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalapiarysitelocation',
            old_name='lat_long',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
