# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-27 10:33
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0022_auto_20200427_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='is_gst_exempt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='oracle_code_application',
            field=models.CharField(default='GGE53 EXEMPT', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
