# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-04 08:56
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0024_auto_20200504_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysite',
            name='proposal_apiary_site_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_sites', to='disturbance.ProposalApiarySiteLocation'),
        ),
        migrations.AlterField(
            model_name='apiarysite',
            name='site_guid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
