# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-08 04:38
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0028_auto_20200505_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
