# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-12 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0030_auto_20200511_1410'),
        ('disturbance', '0030_auto_20200511_1512'),
    ]

    operations = [
    ]
