# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-13 01:45
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0035_auto_20200513_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysitefee',
            name='fee_type',
        ),
        migrations.AddField(
            model_name='apiarysitefeetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apiarysitefeetype',
            name='name',
            field=models.CharField(choices=[('new_application', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('transfer', 'Transfer')], default='new_application', max_length=50),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
