# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-13 02:38
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0036_auto_20200513_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysitefeetype',
            name='name',
            field=models.CharField(choices=[('new_application', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('transfer', 'Transfer')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
