# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-13 05:44
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0039_auto_20200513_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysitefeeremainder',
            name='datetime_expired',
        ),
        migrations.AddField(
            model_name='apiarysitefeeremainder',
            name='date_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
