# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-13 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0031_merge_20200512_0956'),
        ('disturbance', '0041_auto_20200513_1419'),
    ]

    operations = [
    ]
