# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-14 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0042_merge_20200513_1644'),
        ('disturbance', '0024_auto_20200430_1047'),
    ]

    operations = [
    ]
