# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-14 05:53
from __future__ import unicode_literals

import disturbance.components.compliances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0043_merge_20200514_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryChecklistQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer_type', models.CharField(choices=[('yes_no', 'Yes/No type')], default='yes_no', max_length=30, verbose_name='Answer Type')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
    ]
