# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-15 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0044_auto_20200514_0847'),
        ('disturbance', '0044_auto_20200514_1353'),
    ]

    operations = [
    ]
