# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-18 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0044_auto_20200514_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteinformation',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
