# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0045_onsiteinformation_datetime_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalapiarytemporaryuse',
            name='proposal',
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='proposal_apiary_site_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApiarySiteLocation'),
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='temporary_occupier_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='temporary_occupier_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='temporary_occupier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='temporary_occupier_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
