# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0045_apiaryapproversgroup_apiaryassessorsgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiaryApproversGroup',
            new_name='ApiaryApproverGroup',
        ),
        migrations.RenameModel(
            old_name='ApiaryAssessorsGroup',
            new_name='ApiaryAssessorGroup',
        ),
    ]
