# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0046_auto_20200519_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUseApiarySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
                ('proposal_apiary_temporary_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApiaryTemporaryUse')),
            ],
        ),
    ]
