# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0047_temporaryuseapiarysite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalapiarytemporaryuse',
            name='proposal_apiary_site_location',
        ),
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_temporary_use', to='disturbance.Proposal'),
        ),
    ]
