# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0048_auto_20200519_1605'),
        ('disturbance', '0046_auto_20200519_1657'),
    ]

    operations = [
    ]
