# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-19 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0049_merge_20200519_1725'),
        ('disturbance', '0049_auto_20200520_0735'),
    ]

    operations = [
    ]
