# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-20 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0051_auto_20200520_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiarysite',
            old_name='proposal_apiary_site_location',
            new_name='proposal_apiary',
        ),
    ]
