# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0052_auto_20200520_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapiary',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_apiary', to='disturbance.Proposal'),
        ),
    ]
