# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-25 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0046_auto_20200525_1548'),
        ('disturbance', '0053_auto_20200520_1152'),
    ]

    operations = [
    ]
