# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0054_auto_20200520_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaryreferralgroup',
            options={'verbose_name': 'Apiary Referral Group', 'verbose_name_plural': 'Apiary Referral groups'},
        ),
        migrations.RemoveField(
            model_name='apiaryreferralgroup',
            name='default',
        ),
        migrations.RemoveField(
            model_name='apiaryreferralgroup',
            name='region',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_referral_groups', to='disturbance.ApiaryReferralGroup'),
        ),
        migrations.AlterField(
            model_name='apiaryreferralgroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
