# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-26 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0054_merge_20200525_1604'),
        ('disturbance', '0055_auto_20200525_1024'),
    ]

    operations = [
    ]
