# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-26 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0056_merge_20200526_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaryapplicantchecklistanswer',
            name='proposal',
        ),
        migrations.AddField(
            model_name='apiaryapplicantchecklistanswer',
            name='apiary_proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_applicant_checklist', to='disturbance.ProposalApiary'),
            preserve_default=False,
        ),
    ]
