# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0058_auto_20200527_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='temporary_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Site Transfer', 'Site Transfer'), ('Temporary Use', 'Temporary Use'), ('Apiary', 'Apiary')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
