# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-27 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0059_auto_20200527_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysite',
            name='temporary_used',
        ),
    ]
