# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-27 05:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0059_auto_20200527_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_referral', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('referral_text', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='disturbance.ProposalApiary')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_apiary_referalls', to=settings.AUTH_USER_MODEL)),
                ('referral_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_groups', to='disturbance.ApiaryReferralGroup')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disturbance_apiary_assessor_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referral_group',
        ),
    ]
