# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0060_auto_20200527_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaryreferral',
            options={},
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='linked',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='lodged_on',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='referral_text',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='sent_from',
        ),
        migrations.RemoveField(
            model_name='apiaryreferral',
            name='text',
        ),
        migrations.AlterField(
            model_name='apiaryreferral',
            name='referral',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_referral', to='disturbance.Referral'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Site Transfer', 'Site Transfer'), ('Temporary Use', 'Temporary Use'), ('Apiary', 'Apiary')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
