# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-28 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0060_remove_apiarysite_temporary_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuseapiarysite',
            name='proposal_apiary_temporary_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_sites', to='disturbance.ProposalApiaryTemporaryUse'),
        ),
    ]
