# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-29 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0057_auto_20200526_1559'),
        ('disturbance', '0061_auto_20200527_1624'),
    ]

    operations = [
    ]
