# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0062_merge_20200529_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaryapprovergroup',
            name='site',
        ),
        migrations.RemoveField(
            model_name='apiaryassessorgroup',
            name='site',
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('mail', 'Mail'), ('person', 'In Person'), ('referral_complete', 'Referral Completed')], default='email', max_length=20),
        ),
    ]
