# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0064_apiarysiteapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuseapiarysite',
            name='apiary_site_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySiteApproval'),
        ),
    ]
