# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-05 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0065_temporaryuseapiarysite_apiary_site_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuseapiarysite',
            name='apiary_site',
        ),
    ]
