# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0066_remove_temporaryuseapiarysite_apiary_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteapproval',
            name='apiary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_site_approval_set', to='disturbance.ApiarySite'),
        ),
        migrations.AlterField(
            model_name='apiarysiteapproval',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_site_approval_set', to='disturbance.Approval'),
        ),
    ]
