# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-08 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0067_auto_20200605_2106'),
        ('disturbance', '0063_auto_20200605_1422'),
    ]

    operations = [
    ]
