# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0068_merge_20200608_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiarytemporaryuse',
            name='loaning_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval'),
        ),
        migrations.AlterField(
            model_name='temporaryuseapiarysite',
            name='proposal_apiary_temporary_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_sites_approval', to='disturbance.ProposalApiaryTemporaryUse'),
        ),
    ]
