# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0070_auto_20200608_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuseapiarysite',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
