# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0071_temporaryuseapiarysite_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuseapiarysite',
            name='proposal_apiary_temporary_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_use_apiary_sites', to='disturbance.ProposalApiaryTemporaryUse'),
        ),
    ]
