# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0073_auto_20200609_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpolldocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=b''),
        ),
    ]
