# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0074_auto_20200609_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpolldocument',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deed_poll_documents', to='disturbance.ProposalApiary'),
        ),
    ]
