# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0075_auto_20200609_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedpolldocument',
            name='base_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed_poll_documents', to='disturbance.Proposal'),
        ),
    ]
