# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-12 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0076_deedpolldocument_base_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedpolldocument',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed_poll_documents', to='disturbance.ProposalApiary'),
        ),
    ]
