# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-12 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0077_auto_20200612_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disturbance_approvals', to='disturbance.Organisation'),
        ),
    ]
