# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-12 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0077_auto_20200612_0943'),
        ('disturbance', '0078_auto_20200612_1228'),
    ]

    operations = [
    ]
