# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-17 02:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0079_merge_20200612_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='wkb_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
