# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0079_merge_20200612_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='apiary_approval',
            field=models.BooleanField(default=False),
        ),
    ]
