# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-17 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0080_approval_apiary_approval'),
        ('disturbance', '0080_apiarysite_wkb_geometry'),
    ]

    operations = [
    ]
