# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0082_proposalapiarysitetransfer_transferee'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_sites', to='disturbance.Approval'),
        ),
    ]
