# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0083_apiarysite_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('current', 'current'), ('suspended', 'Suspended'), ('not_to_be_reissued', 'not_to_be_reissued'), ('denied', 'denied'), ('vacant', 'vacant')], default='draft', max_length=40),
        ),
    ]
