# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-23 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0083_apiarysite_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiary',
            name='transferee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_transferee', to=settings.AUTH_USER_MODEL),
        ),
    ]
