# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-23 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0084_proposalapiary_transferee'),
        ('disturbance', '0084_apiarysite_status'),
    ]

    operations = [
    ]
