# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-25 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0085_merge_20200623_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiary',
            name='loaning_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval'),
        ),
    ]
