# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-25 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0086_proposalapiary_loaning_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalapiary',
            old_name='loaning_approval',
            new_name='sending_approval',
        ),
    ]
