# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0087_auto_20200625_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaryapplicantchecklistquestion',
            name='checklist_type',
            field=models.CharField(choices=[('Apiary', 'Site Transfer')], default='Apiary', max_length=30, verbose_name='Checklist Type'),
            preserve_default=False,
        ),
    ]
