# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0088_apiaryapplicantchecklistquestion_checklist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryapplicantchecklistquestion',
            name='checklist_type',
            field=models.CharField(choices=[('apiary', 'Apiary'), ('site_transfer', 'Site Transfer')], max_length=30, verbose_name='Checklist Type'),
        ),
    ]
