# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0089_auto_20200625_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTransferApiarySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('apiary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
                ('proposal_apiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_transfer_apiary_sites', to='disturbance.ProposalApiary')),
            ],
        ),
    ]
