# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0090_sitetransferapiarysite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('transfer', 'Transfer'), ('rental', 'Rental')], max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('date_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date_from',),
            },
        ),
    ]
