# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0091_apiaryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='workflow_selected_status',
            field=models.BooleanField(default=False),
        ),
    ]
