# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0092_apiarysite_workflow_selected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryAnnualRentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('date_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date_from',),
            },
        ),
        migrations.DeleteModel(
            name='ApiaryFee',
        ),
        migrations.AlterField(
            model_name='apiarysitefeetype',
            name='name',
            field=models.CharField(choices=[('new_application', 'New Application')], max_length=50, unique=True),
        ),
    ]
