# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0093_auto_20200701_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryAnnualRentFeeRunDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('date_to_run_cron_job', 'Date to run job')], max_length=50, unique=True)),
                ('date_run_cron', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
