# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-02 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0098_auto_20200702_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualrentalfee',
            name='cost',
        ),
    ]
