# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0100_auto_20200702_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualrentalfee',
            name='period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualrentalfee',
            name='period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
