# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-08 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0100_auto_20200702_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetransferapiarysite',
            old_name='selected',
            new_name='internal_selected',
        ),
    ]
