# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-03 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0101_auto_20200703_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryAnnualRentalFeePeriodStartDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('period_start_date', 'Start date of the annual rental fee')], max_length=50, unique=True)),
                ('period_start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('period_start_date',),
            },
        ),
    ]
