# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-06 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0102_apiaryannualrentalfeeperiodstartdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRentalFeePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='annualrentalfee',
            old_name='period_end_date',
            new_name='invoice_period_end_date',
        ),
        migrations.RenameField(
            model_name='annualrentalfee',
            old_name='period_start_date',
            new_name='invoice_period_start_date',
        ),
        migrations.AddField(
            model_name='annualrentalfee',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='annualrentalfee',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_rental_fees', to='disturbance.Approval'),
        ),
        migrations.AlterField(
            model_name='annualrentalfee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_annual_rental_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annualrentalfeeinvoice',
            name='annual_rental_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_rental_fee_invoices', to='disturbance.AnnualRentalFee'),
        ),
        migrations.AddField(
            model_name='annualrentalfee',
            name='annual_rental_fee_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_rental_fees', to='disturbance.AnnualRentalFeePeriod'),
        ),
    ]
