# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-07 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0103_auto_20200706_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRentalFeeApiarySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rental_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.AnnualRentalFee')),
                ('apiary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
            ],
        ),
        migrations.RemoveField(
            model_name='annualrentalfeeinvoice',
            name='annual_rental_fee',
        ),
        migrations.AlterModelOptions(
            name='annualrentalfeeperiod',
            options={'ordering': ['-period_end_date', '-period_start_date']},
        ),
        migrations.DeleteModel(
            name='AnnualRentalFeeInvoice',
        ),
    ]
