# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-08 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0102_sitetransferapiarysite_customer_selected'),
        ('disturbance', '0105_auto_20200707_1038'),
    ]

    operations = [
    ]
