# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-09 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0106_approval_no_annual_rental_fee_until'),
        ('disturbance', '0106_merge_20200708_1552'),
    ]

    operations = [
    ]
