# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-15 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0108_auto_20200710_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalapiary',
            old_name='sending_approval',
            new_name='originating_approval',
        ),
    ]
