# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0109_auto_20200715_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='referral_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_requirement_referral_groups', to='disturbance.ApiaryReferralGroup'),
        ),
    ]
