# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-16 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0111_requirementdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementdocument',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='RequirementDocument',
        ),
    ]
