# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0113_auto_20200718_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='compliance',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='disturbance.Proposal'),
        ),
    ]
