# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-23 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0114_auto_20200723_1005'),
        ('disturbance', '0114_auto_20200722_1456'),
    ]

    operations = [
    ]
