# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0116_compliance_apiary_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='site_transfer_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval'),
        ),
    ]
