# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0117_proposalrequirement_site_transfer_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiary',
            name='target_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_transfer_target_approval', to='disturbance.Approval'),
        ),
        migrations.AlterField(
            model_name='proposalapiary',
            name='originating_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_transfer_originating_approval', to='disturbance.Approval'),
        ),
    ]
