# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-04 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0118_auto_20200727_1113'),
        ('disturbance', '0116_annualrentalfee_lines'),
    ]

    operations = [
    ]
