# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-04 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0119_merge_20200803_1055'),
        ('disturbance', '0119_merge_20200804_0941'),
    ]

    operations = [
    ]
