# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0120_auto_20200803_1523'),
        ('disturbance', '0120_merge_20200804_1434'),
    ]

    operations = [
    ]
