# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0121_merge_20200805_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryChecklistAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiary_checklist', to='disturbance.ProposalApiary')),
            ],
            options={
                'verbose_name': 'CheckList answer',
                'verbose_name_plural': 'CheckList answers',
            },
        ),
        migrations.RenameModel(
            old_name='ApiaryApplicantChecklistQuestion',
            new_name='ApiaryChecklistQuestion',
        ),
        migrations.RemoveField(
            model_name='apiaryapplicantchecklistanswer',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='apiaryapplicantchecklistanswer',
            name='question',
        ),
        migrations.AlterField(
            model_name='apiarysite',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('current', 'Current'), ('suspended', 'Suspended'), ('not_to_be_reissued', 'Not to be Reissued'), ('denied', 'Denied'), ('vacant', 'Vacant')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('assessment_reminder_days', 'Assessment reminder days'), ('oracle_code_apiary_site_annural_rental_fee', 'Oracle code for the apiary site annual rental fee')], max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ApiaryApplicantChecklistAnswer',
        ),
        migrations.AddField(
            model_name='apiarychecklistanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='disturbance.ApiaryChecklistQuestion'),
        ),
    ]
