# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-06 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0124_apiarychecklistanswer_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarychecklistanswer',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_checklist_referral', to='disturbance.ApiaryReferral'),
        ),
    ]
