# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0124_apiarysite_wkb_geometry_applied'),
        ('disturbance', '0127_auto_20200810_0951'),
    ]

    operations = [
    ]
