# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0129_apiaryorganisationaccessgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequest',
            name='template_group',
            field=models.CharField(choices=[('apiary', 'Apiary'), ('das', 'DAS')], default='das', max_length=100),
        ),
    ]
