# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-17 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0129_auto_20200814_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaryglobalsettings',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='apiary_licence'),
        ),
        migrations.AlterField(
            model_name='apiaryglobalsettings',
            name='key',
            field=models.CharField(choices=[('oracle_code_apiary_site_annural_rental_fee', 'Oracle code for the apiary site annual rental fee'), ('apiary_sites_list_token', 'Token to import the apiary sites list'), ('apiary_licence_template_file', 'Apiary licence template file')], max_length=255, unique=True),
        ),
    ]
