# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-19 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0130_organisationrequest_template_group'),
        ('disturbance', '0131_auto_20200818_1409'),
    ]

    operations = [
    ]
