# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-19 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0131_auto_20200818_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysitefeetype',
            name='name',
            field=models.CharField(choices=[('new_application', 'New Application'), ('renewal', 'Renewal'), ('transfer', 'Transfer')], max_length=50, unique=True),
        ),
    ]
