# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-19 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0132_merge_20200819_1053'),
        ('disturbance', '0132_auto_20200819_1327'),
    ]

    operations = [
    ]
