# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-21 08:14
from __future__ import unicode_literals

import disturbance.components.approvals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0133_merge_20200819_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(upload_to=disturbance.components.approvals.models.update_approval_doc_filename)),
                ('can_delete', models.BooleanField(default=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_documents', to='disturbance.Approval')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='apiary_renewal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apiary_renewal_document', to='disturbance.RenewalDocument'),
        ),
    ]
