# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-27 01:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0134_auto_20200821_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='wkb_geometry_pending',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
