# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-31 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0135_apiarysite_wkb_geometry_pending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiarychecklistquestion',
            options={'ordering': ['order', 'id']},
        ),
    ]
