# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-03 06:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0138_districtdbca'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='proposal_apiaries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
