# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-03 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0139_apiarysite_proposal_apiaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiarysite',
            old_name='proposal_apiaries',
            new_name='proposal_apiary_ids',
        ),
    ]
