# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-04 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0144_remove_proposalapiary_vacant_apiary_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='proposal_apiaries',
            field=models.ManyToManyField(related_name='vacant_apiary_sites', to='disturbance.ProposalApiary'),
        ),
    ]
