# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-08 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0145_apiarysite_proposal_apiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysite',
            name='pending_payment',
            field=models.BooleanField(default=False),
        ),
    ]
