# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0145_apiarysite_proposal_apiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='system',
            field=models.CharField(choices=[('disturbance', 'Disturbance'), ('apiary', 'Apiary')], default='disturbance', max_length=20, verbose_name='System'),
        ),
    ]
