# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0146_apiarysite_pending_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiarySiteOnProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiary_site_status_when_submitted', models.CharField(blank=True, max_length=40)),
                ('apiary_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
                ('proposal_apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApiary')),
            ],
        ),
        migrations.AddField(
            model_name='proposalapiary',
            name='beehive_sites',
            field=models.ManyToManyField(related_name='proposal_apiary_set', through='disturbance.ApiarySiteOnProposal', to='disturbance.ApiarySite'),
        ),
    ]
