# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-10 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0147_auto_20200910_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiarySiteOnApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiary_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='beehive_sites',
            field=models.ManyToManyField(related_name='approval_set', through='disturbance.ApiarySiteOnApproval', to='disturbance.ApiarySite'),
        ),
    ]
