# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-10 02:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0148_auto_20200910_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiarySiteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('approved', 'Approved')], default='draft', max_length=40)),
                ('apiary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Approval')),
                ('proposal_apiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ProposalApiary')),
            ],
        ),
    ]
