# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-11 00:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0152_auto_20200910_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='wkb_geometry_draft',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='wkb_geometry_processed',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
