# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-11 01:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0153_auto_20200911_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonapproval',
            name='wkb_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
