# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-15 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0157_categorydbca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysite',
            name='site_category',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='wkb_geometry',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='wkb_geometry_applied',
        ),
        migrations.RemoveField(
            model_name='apiarysite',
            name='wkb_geometry_pending',
        ),
    ]
