# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-15 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0159_auto_20200915_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysiteonapproval',
            name='link_connected',
        ),
        migrations.RemoveField(
            model_name='apiarysiteonproposal',
            name='link_connected',
        ),
        migrations.AddField(
            model_name='apiarysite',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
    ]
