# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-17 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0146_proposalstandardrequirement_system'),
        ('disturbance', '0160_auto_20200915_1032'),
    ]

    operations = [
    ]
