# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-17 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0161_merge_20200915_1504'),
        ('disturbance', '0163_apiarysiteonapproval_site_category'),
    ]

    operations = [
    ]
