# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0163_apiarysiteonapproval_site_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='site_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pending_payment', 'Pending payment'), ('approved', 'Approved'), ('denied', 'Denied'), ('current', 'Current'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
