# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-21 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0164_auto_20200918_1437'),
        ('disturbance', '0164_merge_20200918_0131'),
    ]

    operations = [
    ]
