# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0165_merge_20200921_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='making_payment',
            field=models.BooleanField(default=False),
        ),
    ]
