# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0166_apiarysiteonproposal_making_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='site_status',
            field=models.CharField(default=b'current', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='site_status',
            field=models.CharField(default=b'draft', max_length=20),
        ),
    ]
