# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0167_auto_20200922_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonapproval',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
