# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0168_migratedapiarylicences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratedapiarylicences',
            name='permit_number',
            field=models.IntegerField(unique=True),
        ),
    ]
