# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0169_auto_20200922_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MigratedApiaryLicences',
            new_name='MigratedApiaryLicence',
        ),
    ]
