# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0170_auto_20200922_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratedapiarylicence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='migratedapiarylicence',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='migratedapiarylicence',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
