# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0171_auto_20200922_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratedapiarylicence',
            name='licencee_type',
            field=models.CharField(choices=[('organisation', 'Organisation'), ('individual', 'Individual')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
