# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-22 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0168_apiarysiteonapproval_available'),
        ('disturbance', '0172_migratedapiarylicence_licencee_type'),
    ]

    operations = [
    ]
