# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0173_merge_20200922_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
