# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-23 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0173_merge_20200922_1657'),
        ('disturbance', '0169_auto_20200923_1709'),
    ]

    operations = [
    ]
