# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-24 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0174_merge_20200923_1711'),
        ('disturbance', '0174_auto_20200924_1641'),
    ]

    operations = [
    ]
