# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-25 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0174_merge_20200923_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsiteinformation',
            name='apiary_site',
        ),
        migrations.AddField(
            model_name='onsiteinformation',
            name='apiary_site_on_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySiteOnApproval'),
        ),
    ]
