# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0175_auto_20200925_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysite',
            name='approval_link_for_vacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacant_apiary_site', to='disturbance.ApiarySiteOnApproval'),
        ),
        migrations.AlterField(
            model_name='apiarysite',
            name='proposal_link_for_vacant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacant_apiary_site', to='disturbance.ApiarySiteOnProposal'),
        ),
    ]
