# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-30 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0177_apiarysiteonproposal_for_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiarysiteonapproval',
            name='site_available',
        ),
    ]
