# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0179_auto_20201001_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetransferapiarysite',
            name='apiary_site',
        ),
        migrations.AddField(
            model_name='sitetransferapiarysite',
            name='apiary_site_on_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySiteOnApproval'),
        ),
    ]
