# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-05 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0175_merge_20200924_1648'),
        ('disturbance', '0181_auto_20201002_1123'),
    ]

    operations = [
    ]
