# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-05 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0183_renewaldocument_for_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewaldocument',
            name='for_expiry_date',
        ),
    ]
