# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-05 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0184_remove_renewaldocument_for_expiry_date'),
        ('disturbance', '0182_merge_20201005_0959'),
    ]

    operations = [
    ]
