# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0187_wacoast_smoothed'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='sitetransfer_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetransferapproval_requirement', to='disturbance.Approval'),
        ),
        migrations.AlterField(
            model_name='proposalrequirement',
            name='apiary_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposalrequirement_set', to='disturbance.Approval'),
        ),
    ]
