# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0188_auto_20201012_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiary',
            name='transferee_email_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
