# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0190_auto_20201027_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarychecklistanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiarychecklistquestion',
            name='checklist_type',
            field=models.CharField(choices=[('apiary', 'Apiary'), ('apiary_per_site', 'Apiary per site'), ('site_transfer', 'Site Transfer'), ('site_transfer_per_site', 'Site Transfer per site')], max_length=30, verbose_name='Checklist Type'),
        ),
    ]
