# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0191_auto_20201027_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarychecklistanswer',
            name='apiary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.ApiarySite'),
        ),
    ]
