# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-27 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0190_apiarysiteonproposal_application_fee_paid'),
        ('disturbance', '0192_apiarychecklistanswer_apiary_site'),
    ]

    operations = [
    ]
