# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0193_merge_20201027_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryannualrentalfeeperiodstartdate',
            name='name',
            field=models.CharField(choices=[('period_start_date', 'Start date of the annual site fee')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='apiaryglobalsettings',
            name='key',
            field=models.CharField(choices=[('oracle_code_apiary_site_annural_rental_fee', 'Oracle code for the apiary site annual site fee'), ('apiary_sites_list_token', 'Token to import the apiary sites list'), ('apiary_licence_template_file', 'Apiary licence template file')], max_length=255, unique=True),
        ),
    ]
