# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0194_auto_20201027_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalapiary',
            name='target_approval_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Organisation'),
        ),
    ]
