# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-05 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0196_auto_20201103_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='self_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_current_state', to='disturbance.Proposal'),
        ),
        migrations.AddField(
            model_name='proposalapiary',
            name='self_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disturbance.ProposalApiary'),
        ),
    ]
