# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-06 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0197_auto_20201105_1557'),
        ('disturbance', '0198_supportingapplicationdocument'),
    ]

    operations = [
    ]
