# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0199_merge_20201106_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='self_clone',
        ),
        migrations.RemoveField(
            model_name='proposalapiary',
            name='self_clone',
        ),
        migrations.AddField(
            model_name='proposalapiary',
            name='reissue_originating_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalapiary',
            name='reissue_target_approval',
            field=models.BooleanField(default=False),
        ),
    ]
