# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-06 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0200_auto_20201106_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalapiarysitetransfer',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalapiarysitetransfer',
            name='transferee',
        ),
        migrations.DeleteModel(
            name='ProposalApiarySiteTransfer',
        ),
    ]
