# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0203_auto_20201109_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicliabilityinsurancedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
