# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0204_publicliabilityinsurancedocument_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicliabilityinsurancedocument',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='proposalapiary',
            name='public_liability_insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
