# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-17 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0205_auto_20201109_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryglobalsettings',
            name='key',
            field=models.CharField(choices=[('oracle_code_apiary_site_annural_rental_fee', 'Oracle code for the apiary site annual site fee'), ('apiary_sites_list_token', 'Token to import the apiary sites list'), ('apiary_licence_template_file', 'Apiary licence template file'), ('print_deed_poll_url', 'URL of the deed poll')], max_length=255, unique=True),
        ),
    ]
