# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-25 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0206_auto_20201117_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='apiary_site_is_vacant_when_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
