# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0207_apiarysiteonproposal_apiary_site_is_vacant_when_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='site_status',
            field=models.CharField(default='current', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='site_status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='deedpolldocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicliabilityinsurancedocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supportingapplicationdocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='temporarydocument',
            name='_file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
