# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-12-07 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0208_auto_20201127_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaryannualrentalfee',
            options={'ordering': ('date_from',), 'verbose_name': 'Annual Site Fee'},
        ),
    ]
