# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0211_auto_20201211_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='weekly_reminder_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
