# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0211_auto_20201211_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='site_status',
            field=models.CharField(db_index=True, default='draft', max_length=20),
        ),
    ]
