# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0212_auto_20210112_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='site_status',
            field=models.CharField(db_index=True, default='current', max_length=20),
        ),
    ]
