# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0213_auto_20210112_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaryreferral',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apiary_referrals_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
