# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 06:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0215_merge_20210202_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='fee_invoice_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), null=True, size=None),
        ),
    ]
