# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 07:29
from __future__ import unicode_literals

import disturbance.components.proposals.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0216_proposal_fee_invoice_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='fee_invoice_reference',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='fee_invoice_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), default=disturbance.components.proposals.models.fee_invoice_references_default, null=True, size=None),
        ),
    ]
