# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0220_auto_20210224_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='parent_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.QuestionOption'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_question', to='disturbance.MasterlistQuestion'),
        ),
    ]
