# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0222_auto_20210226_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_text_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('isCopiedToPermit', 'isCopiedToPermit'), ('isRequired', 'isRequired'), ('canBeEditedByAssessor', 'canBeEditedByAssessor'), ('isRepeatable', 'isRepeatable')], max_length=400, null=True),
        ),
    ]
