# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0223_auto_20210226_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_text_assessor_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
