# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-05 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0226_auto_20210305_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionquestion',
            name='parent_answer',
        ),
    ]
