# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 02:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0232_auto_20210318_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_tex',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_tex_assessor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_text_assessor_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterlistquestion',
            name='help_text_url',
            field=models.BooleanField(default=False),
        ),
    ]
