# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-26 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0235_auto_20210326_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Apiary', 'Apiary'), ('Temporary Use', 'Temporary Use'), ('Site Transfer', 'Site Transfer'), ('Prescribed Burning', 'Prescribed Burning')], max_length=64, verbose_name='Application Type name'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Prescribed Burning', 'Prescribed Burning'), ('Site Transfer', 'Site Transfer'), ('Temporary Use', 'Temporary Use'), ('Apiary', 'Apiary')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
