# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0240_auto_20210408_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
