# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0241_sectionquestion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterlistquestion',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='masterlistquestion',
            name='help_text_assessor',
        ),
    ]
