# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 03:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0245_auto_20210409_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterlistquestion',
            name='help_text_assessor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
