# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0248_sectionquestion_parent_question_another'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionquestion',
            name='parent_question_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.MasterlistQuestion'),
        ),
    ]
