# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 12:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0250_remove_sectionquestion_parent_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='parent_question',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='section', chained_model_field='question_sections__section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_question', to='disturbance.MasterlistQuestion'),
        ),
    ]
