# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0251_auto_20210411_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionquestion',
            name='parent_question_another',
        ),
    ]
