# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0252_remove_sectionquestion_parent_question_another'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
