# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0254_auto_20210528_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlistquestion',
            name='property_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Prescribed Burning', 'Prescribed Burning'), ('Site Transfer', 'Site Transfer'), ('Temporary Use', 'Temporary Use'), ('Apiary', 'Apiary')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
