# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 02:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0255_auto_20210419_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionquestion',
            name='parent_answer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='parent_question', chained_model_field='masterlistquestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='disturbance.QuestionOption'),
        ),
    ]
