# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0257_auto_20210420_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='licensed_site',
            field=models.BooleanField(default=False),
        ),
    ]
