# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0261_auto_20210609_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='approval_cpc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='approval_minister_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='batch_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
