# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0262_auto_20210708_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='catchment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='cog',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='dra_permit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='forest_block',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='map_ref',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='roadtrack',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='apiarysiteonproposal',
            name='zone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
