# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0263_auto_20210708_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='approval_cpc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiarysiteonproposal',
            name='approval_minister_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
