# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-01 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0256_sectionquestion_property_cache'),
        ('disturbance', '0267_auto_20210711_1208'),
    ]

    operations = [
    ]
