# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-24 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0256_sectionquestion_property_cache'),
        ('disturbance', '0268_auto_20210806_1636'),
    ]

    operations = [
    ]
