# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-29 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0269_merge_20210924_1559'),
        ('disturbance', '0268_merge_20211001_1450'),
    ]

    operations = [
    ]
