# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0272_maplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlistquestion',
            name='option',
            field=models.ManyToManyField(blank=True, to='disturbance.QuestionOption'),
        ),
    ]
