# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-02 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0273_auto_20211102_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='availability',
        ),
    ]
