# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-08 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0272_temporaryusepublicliabilityinsurancedocument'),
        ('disturbance', '0274_remove_maplayer_availability'),
    ]

    operations = [
    ]
