# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0275_merge_20211108_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'verbose_name': 'apiary map layer'},
        ),
        migrations.AddField(
            model_name='apiaryreferralgroup',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', default=1, on_delete=django.db.models.deletion.CASCADE, to='disturbance.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiaryreferralgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='disturbance.Region'),
        ),
    ]
