# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0275_merge_20211108_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'apiary map column',
            },
        ),
        migrations.AlterModelOptions(
            name='maplayer',
            options={'verbose_name': 'apiary map layer'},
        ),
        migrations.AddField(
            model_name='mapcolumn',
            name='map_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.MapLayer'),
        ),
    ]
