# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0276_auto_20211110_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteinformation',
            name='flora',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onsiteinformation',
            name='hives_loc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onsiteinformation',
            name='hives_num',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsiteinformation',
            name='people_names',
            field=models.TextField(blank=True),
        ),
    ]
