# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0276_auto_20211122_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='display_all_columns',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mapcolumn',
            name='map_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='disturbance.MapLayer'),
        ),
    ]
