# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0277_auto_20211122_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcolumn',
            name='option_for_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapcolumn',
            name='option_for_internal',
            field=models.BooleanField(default=True),
        ),
    ]
