# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0277_auto_20211110_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsiteinformation',
            name='hives_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
