# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-25 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0279_auto_20211116_1812'),
        ('disturbance', '0278_auto_20211122_1614'),
    ]

    operations = [
    ]
