# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-11 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0280_merge_20211125_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaryannualrentalfee',
            old_name='amount',
            new_name='amount_south_west',
        ),
    ]
