# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-11 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0281_auto_20220111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaryannualrentalfee',
            name='amount_remote',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
