# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-21 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0281_proposalmapdocument'),
        ('disturbance', '0282_apiaryannualrentalfee_amount_remote'),
    ]

    operations = [
    ]
