# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0282_apiaryannualrentalfee_amount_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysite',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
