# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0283_merge_20220207_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialQueryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_mlq', models.CharField(max_length=100, verbose_name='Answer (Masterlist Question)')),
                ('layer_name', models.CharField(max_length=100)),
                ('layer_url', models.CharField(blank=True, max_length=512, null=True)),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('visible_to_proponent', models.BooleanField(default=False)),
                ('buffer', models.PositiveIntegerField(blank=True, null=True)),
                ('how', models.CharField(choices=[('Overlapping', 'Overlapping'), ('Outside', 'Outside')], default='Overlapping', max_length=40, verbose_name='Overlapping/Outside')),
                ('column_name', models.CharField(max_length=100, verbose_name='Name of layer attribute/field')),
                ('operator', models.CharField(choices=[('Equals', 'Equals'), ('GreaterThan', 'Greather than'), ('LessThan', 'Less than'), ('IsNull', 'Is null'), ('IsNotNull', 'Is not null')], default='Equals', max_length=40, verbose_name='Operator')),
                ('value', models.CharField(max_length=100)),
                ('prefix_answer', models.TextField(blank=True, null=True)),
                ('no_polygons_proponent', models.IntegerField(default=-1, verbose_name='No. of polygons to process (Proponent)')),
                ('answer', models.TextField(blank=True, null=True)),
                ('prefix_info', models.CharField(blank=True, max_length=100, null=True)),
                ('no_polygons_assessor', models.IntegerField(default=-1, verbose_name='No. of polygons to process (Assessor)')),
                ('assessor_info', models.TextField(blank=True, null=True)),
                ('regions', models.CharField(choices=[('All', 'All')], default='All', max_length=40, verbose_name='Regions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='disturbance.MasterlistQuestion')),
            ],
        ),
    ]
