# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0283_auto_20220609_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaryannualrentalfeeperiodstartdate',
            options={'ordering': ('period_start_date',), 'verbose_name': 'Annual Site Fee Priod Start Date'},
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeeperiodstartdate',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='Although Year, month and day are entered, the system uses only the month and the day internally', null=True),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='date_run_cron',
            field=models.DateField(blank=True, help_text='Although Year, month and day are entered, the system uses only the month and the day internally', null=True),
        ),
    ]
