# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0283_merge_20220209_1842'),
        ('disturbance', '0284_proposal_shapefile_json'),
    ]

    operations = [
    ]
