# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0284_auto_20220622_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaryannualrentalfeerundate',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeeperiodstartdate',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='Although year, month and day are entered, the system uses only the month and the day internally', null=True),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='date_run_cron',
            field=models.DateField(blank=True, help_text='Although year, month and day are entered, the system uses only the month and the day internally', null=True),
        ),
    ]
