# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0285_auto_20220622_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiaryannualrentalfeeperiodstartdate',
            options={'ordering': ('period_start_date',), 'verbose_name': 'Annual Site Fee Period Start Date'},
        ),
        migrations.AddField(
            model_name='apiaryannualrentalfeerundate',
            name='enabled_for_new_site',
            field=models.BooleanField(default=False, help_text='Sets whether the annual fee is applied to newly added sites when an application is approved'),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeeperiodstartdate',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='Although year, month and date are entered, the system uses only the month and the date internally', null=True),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='date_run_cron',
            field=models.DateField(blank=True, help_text='Although year, month and date are entered, the system uses only the month and the date internally', null=True),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Sets whether the annual fee is applied to already existing sites'),
        ),
    ]
