# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-10 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0285_spatialqueryquestion'),
        ('disturbance', '0283_merge_20220209_1842'),
    ]

    operations = [
    ]
