# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-09 02:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0285_spatialqueryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='add_info_applicant',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
