# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0286_merge_20220210_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='answer_mlq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_options', to='disturbance.QuestionOption'),
        ),
    ]
