# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0286_auto_20220628_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Sets whether the annual fee is applied to the existing sites by the cron job'),
        ),
        migrations.AlterField(
            model_name='apiaryannualrentalfeerundate',
            name='enabled_for_new_site',
            field=models.BooleanField(default=False, help_text='Sets whether the annual fee is applied when an application is approved'),
        ),
    ]
