# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-27 03:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0287_proposal_add_info_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='layer_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
