# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0288_auto_20220628_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiarysiteonapproval',
            name='dra_permit',
            field=models.NullBooleanField(),
        ),
    ]
