# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-25 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0288_auto_20220323_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='answer_mlq',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='question',
        ),
    ]
