# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0289_auto_20220525_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='answer_mlq',
            field=models.CharField(default='abc', max_length=512, verbose_name='Answer (Masterlist Question)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='question',
            field=models.TextField(default='def', verbose_name='Question (Masterlist Question)'),
            preserve_default=False,
        ),
    ]
