# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-11 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0289_auto_20220701_1046'),
        ('disturbance', '0289_auto_20220706_1458'),
    ]

    operations = [
    ]
