# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-01 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0288_proposal_layer_data'),
        ('disturbance', '0290_auto_20220525_1653'),
    ]

    operations = [
    ]
