# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0290_merge_20220711_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Disturbance Training', 'Disturbance Training'), ('Disturbance Demo', 'Disturbance Demo'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Apiary', 'Apiary'), ('Temporary Use', 'Temporary Use'), ('Site Transfer', 'Site Transfer'), ('Prescribed Burning', 'Prescribed Burning')], max_length=64, verbose_name='Application Type name'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Disturbance Training', 'Disturbance Training'), ('Disturbance Demo', 'Disturbance Demo'), ('Powerline Maintenance', 'Powerline Maintenance'), ('Apiary', 'Apiary'), ('Temporary Use', 'Temporary Use'), ('Site Transfer', 'Site Transfer'), ('Prescribed Burning', 'Prescribed Burning')], default='Disturbance', max_length=64, verbose_name='Application name (eg. Disturbance, Apiary)'),
        ),
    ]
