# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0291_merge_20220701_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='value_type',
            field=models.CharField(blank=True, choices=[('Text', 'Text String'), ('Int', 'Integer'), ('Float', 'Float')], max_length=40, null=True, verbose_name='Value type'),
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='widget_type',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Multi-Select', 'Multi select'), ('Radio button', 'Radio button'), ('Checkbox', 'Checkbox')], max_length=40, null=True, verbose_name='Component type'),
        ),
    ]
