# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0291_auto_20230221_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reissued',
            field=models.BooleanField(default=False),
        ),
    ]
