# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-16 03:12
from __future__ import unicode_literals

import disturbance.components.approvals.models
import disturbance.components.compliances.models
import disturbance.components.organisations.models
import disturbance.components.proposals.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0292_proposal_reissued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymatrix',
            options={'verbose_name_plural': 'Approval matrix'},
        ),
        migrations.AlterField(
            model_name='amendmentrequestdocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.proposals.models.update_amendment_request_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvaldocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.approvals.models.update_approval_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvallogdocument',
            name='_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.approvals.models.update_approval_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='compliancelogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.compliances.models.update_compliance_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='deedpolldocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisationlogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.organisations.models.update_organisation_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to='organisation/requests/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='organisationrequestlogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.organisations.models.update_organisation_request_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='proposalapiarydocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.proposals.models.update_apiary_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='_file',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposallogdocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.proposals.models.update_proposal_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='publicliabilityinsurancedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='renewaldocument',
            name='_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=disturbance.components.approvals.models.update_approval_doc_filename),
        ),
        migrations.AlterField(
            model_name='supportingapplicationdocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='temporaryusepublicliabilityinsurancedocument',
            name='_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/var/www/das_gis/private-media/'), upload_to=''),
        ),
    ]
