# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0292_auto_20220919_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='value_type',
            field=models.CharField(choices=[('', ''), ('Text', 'Text String'), ('Int', 'Integer'), ('Float', 'Float')], default='', max_length=40, verbose_name='Value type'),
        ),
    ]
