# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0293_auto_20220919_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialqueryquestion',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Radio button priority'),
        ),
    ]
