# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-04 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0292_auto_20230227_1044'),
        ('disturbance', '0290_merge_20220711_1715'),
        ('disturbance', '0294_auto_20220921_1058'),
    ]

    operations = [
    ]
