# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-01 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0291_auto_20230221_1433'),
        ('disturbance', '0295_merge_20230404_1049'),
    ]

    operations = [
    ]
