# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-19 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0295_merge_20230404_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASMapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('layer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('layer_url', models.CharField(blank=True, max_length=256, null=True)),
                ('option_for_internal', models.BooleanField(default=True)),
                ('option_for_external', models.BooleanField(default=True)),
                ('display_all_columns', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Disturbance map layer',
            },
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='value_type',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='widget_type',
        ),
    ]
