# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-09-15 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0295_auto_20240727_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmonitor',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('REFRESH', 'REFRESH'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE')], default='FULL', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spatialquerylayer',
            name='how',
            field=models.CharField(choices=[('Overlapping', 'Overlapping'), ('Outside', 'Outside'), ('Inside', 'Inside')], default='Overlapping', max_length=40, verbose_name='Overlapping/Outside/Inside'),
        ),
        migrations.AlterField(
            model_name='spatialquerymetrics',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('REFRESH', 'REFRESH'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE')], max_length=40),
        ),
    ]
