# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-10-07 08:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0296_auto_20240915_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='help_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='help_text_required',
            field=models.BooleanField(default=False),
        ),
    ]
