# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-16 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0296_merge_20230501_0840'),
        ('disturbance', '0296_auto_20230419_1115'),
    ]

    operations = [
    ]
