# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0297_merge_20230516_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='disturbance.DASMapLayer'),
            #preserve_default=False,
        ),
    ]
