# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 01:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0297_merge_20230516_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='refresh_timestamp',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
