# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-10-21 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0297_auto_20241007_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialquerymetrics',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE'), ('REFRESH_PARTIAL', 'REFRESH_PARTIAL'), ('REFRESH_SINGLE', 'REFRESH_SINGLE'), ('TEST_GROUP', 'TEST_GROUP'), ('TEST_SINGLE', 'TEST_SINGLE')], max_length=40),
        ),
        migrations.AlterField(
            model_name='taskmonitor',
            name='request_type',
            field=models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE'), ('REFRESH_PARTIAL', 'REFRESH_PARTIAL'), ('REFRESH_SINGLE', 'REFRESH_SINGLE'), ('TEST_GROUP', 'TEST_GROUP'), ('TEST_SINGLE', 'TEST_SINGLE')], max_length=40),
        ),
        migrations.AlterField(
            model_name='taskmonitor',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('max_queue_time', 'Max_Queue_Time_Reached'), ('max_running_time', 'Max_Running_Time_Reached'), ('max_retries', 'Max_Retries_Reached')], default='created', max_length=32, verbose_name='Task Status'),
        ),
    ]
