# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-31 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0298_auto_20230516_1516'),
        ('disturbance', '0298_auto_20230525_0936'),
    ]

    operations = [
    ]
