# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0298_auto_20241021_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='prefill_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitymatrix',
            name='name',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Ecological Thinning', 'Ecological Thinning')], default='Disturbance', max_length=24, verbose_name='Activity matrix name'),
        ),
    ]
