# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0299_auto_20230529_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='disturbance.CddpQuestionGroup'),
            preserve_default=False,
        ),
    ]
