# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-08 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0299_merge_20230531_1621'),
        ('disturbance', '0300_auto_20230529_1606'),
    ]

    operations = [
    ]
