# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-09 03:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0301_merge_20230608_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='history_add_info_assessor',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
