# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-13 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0302_auto_20230609_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='layer_name',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='layer_url',
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='disturbance.DASMapLayer'),
            preserve_default=False,
        ),
    ]
