# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0304_auto_20230623_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='prefill_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
