# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-11 02:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0306_auto_20230705_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='gis_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
