# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0307_auto_20230711_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmaplayer',
            name='cache_expiry',
            field=models.IntegerField(default=300),
        ),
    ]
