# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0308_auto_20230904_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
