# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-12 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0308_auto_20230904_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='answer_mlq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_options', to='disturbance.QuestionOption'),
        ),
        migrations.AlterField(
            model_name='spatialqueryquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='disturbance.MasterlistQuestion'),
        ),
    ]
