# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-11 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0310_auto_20231006_1520'),
        ('disturbance', '0309_auto_20231006_1611'),
        ('disturbance', '0292_proposal_reissued'),
    ]

    operations = [
    ]
