# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-11 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0311_merge_20231011_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialQueryMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('system', models.CharField(max_length=64, verbose_name='Application System Name')),
                ('request_type', models.CharField(choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('SINGLE', 'SINGLE')], max_length=40)),
                ('sqs_response', django.contrib.postgres.fields.jsonb.JSONField(default=[{}], verbose_name='Response from SQS')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='disturbance.Proposal')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
