# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-13 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0312_auto_20231012_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialquerymetrics',
            name='time_taken',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Total time for request/response'),
            preserve_default=False,
        ),
    ]
