# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-16 02:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0313_auto_20231013_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='assessor_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}], verbose_name='Assessor response set'),
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='proponent_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}], verbose_name='Proponent response set'),
        ),
    ]
