# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-10-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0314_auto_20231016_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialquerymetrics',
            name='response_cached',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('assessment_reminder_days', 'Assessment reminder days'), ('das_sharepoint_page', 'DAS Sharepoint page'), ('proposal_assess_help_page', 'DAS Proposal assess help page'), ('compliance_assess_help_page', 'DAS compliance assess help page'), ('referral_assess_help_page', 'DAS referral assess help page')], max_length=255, unique=True),
        ),
    ]
