# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-11-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0316_auto_20231116_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('assessment_reminder_days', 'Assessment reminder days'), ('das_sharepoint_page', 'DAS Sharepoint page'), ('proposal_assess_help_page', 'DAS Proposal assess help page'), ('compliance_assess_help_page', 'DAS compliance assess help page'), ('referral_assess_help_page', 'DAS referral assess help page'), ('proposal_approver_help_page', 'DAS Proposal approver help page'), ('shapefile_info', 'Shapefile further information'), ('region_help_url', 'Region help url'), ('district_help_url', 'District help url'), ('activity_type_help_url', 'Activity type help url'), ('sub_activity_1_help_url', 'Sub activity 1 help url'), ('sub_activity_2_help_url', 'Sub activity 2 help url'), ('category_help_url', 'Category help url')], max_length=255, unique=True),
        ),
    ]
