# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-04 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0318_auto_20231127_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cddpquestiongroup',
            options={'verbose_name': 'Spatial Question Group'},
        ),
    ]
