# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-15 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0319_auto_20231204_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error'), ('max_retries', 'Max_Retries_Reached')], default='created', max_length=12, verbose_name='Task Status')),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disturbance.Proposal')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Monitor',
            },
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='show_add_info_section_prop',
            field=models.BooleanField(default=False, verbose_name='Show additional info section (Proponent)'),
        ),
    ]
