# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-19 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0321_auto_20240110_1454'),
        ('disturbance', '0320_auto_20240115_1650'),
    ]

    operations = [
    ]
