# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-12 03:17
from __future__ import unicode_literals

import disturbance.components.approvals.models
import disturbance.components.compliances.models
import disturbance.components.organisations.models
import disturbance.components.proposals.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disturbance', '0323_auto_20240328_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(max_length=255, upload_to=disturbance.components.proposals.models.export_file_path)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disturbance.Proposal')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
