# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-24 04:01
from __future__ import unicode_literals

import disturbance.components.approvals.models
import disturbance.components.compliances.models
import disturbance.components.organisations.models
import disturbance.components.proposals.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0324_auto_20240412_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
