# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-10 05:05
from __future__ import unicode_literals

import disturbance.components.approvals.models
import disturbance.components.compliances.models
import disturbance.components.organisations.models
import disturbance.components.proposals.models
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0325_auto_20240424_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialQueryLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('visible_to_proponent', models.BooleanField(default=False)),
                ('buffer', models.PositiveIntegerField(blank=True, null=True)),
                ('how', models.CharField(choices=[('Overlapping', 'Overlapping'), ('Outside', 'Outside')], default='Overlapping', max_length=40, verbose_name='Overlapping/Outside')),
                ('column_name', models.CharField(max_length=100, verbose_name='Name of layer attribute/field')),
                ('operator', models.CharField(choices=[('Equals', 'Equals'), ('Contains', 'Contains'), ('OR', 'OR'), ('Like', 'Like'), ('GreaterThan', 'Greather than'), ('LessThan', 'Less than'), ('IsNotNull', 'Is not null')], default='Equals', max_length=40, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix_answer', models.TextField(blank=True, null=True)),
                ('no_polygons_proponent', models.IntegerField(blank=True, default=-1, verbose_name='No. of polygons to process (Proponent)')),
                ('answer', models.TextField(blank=True, null=True)),
                ('prefix_info', models.CharField(blank=True, max_length=100, null=True)),
                ('no_polygons_assessor', models.IntegerField(blank=True, default=-1, verbose_name='No. of polygons to process (Assessor)')),
                ('assessor_info', models.TextField(blank=True, null=True)),
                ('proponent_items', django.contrib.postgres.fields.jsonb.JSONField(default=[{}], verbose_name='Proponent response set')),
                ('assessor_items', django.contrib.postgres.fields.jsonb.JSONField(default=[{}], verbose_name='Assessor response set')),
                ('regions', models.CharField(blank=True, choices=[('All', 'All')], default='All', max_length=40, verbose_name='Regions')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='disturbance.DASMapLayer')),
            ],
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='assessor_info',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='assessor_items',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='buffer',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='how',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='no_polygons_assessor',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='no_polygons_proponent',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='prefix_answer',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='prefix_info',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='proponent_items',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='show_add_info_section_prop',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='value',
        ),
        migrations.RemoveField(
            model_name='spatialqueryquestion',
            name='visible_to_proponent',
        ),
        migrations.AddField(
            model_name='spatialqueryquestion',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional/Misc Data'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='shapefile_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Source/Submitter (multi) polygon geometry'),
        ),
        migrations.AddField(
            model_name='spatialquerylayer',
            name='spatial_query_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_query_layers', to='disturbance.SpatialQueryQuestion'),
        ),
    ]
