# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-06-17 09:09
from __future__ import unicode_literals

import disturbance.components.approvals.models
import disturbance.components.compliances.models
import disturbance.components.organisations.models
import disturbance.components.proposals.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disturbance', '0326_auto_20240610_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialquerylayer',
            name='no_polygons_assessor',
        ),
        migrations.RemoveField(
            model_name='spatialquerylayer',
            name='no_polygons_proponent',
        ),
        migrations.RemoveField(
            model_name='spatialquerylayer',
            name='regions',
        )
    ]
