# Generated by Django 5.0.8 on 2024-09-27 02:13

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20240716_1530'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuserlogentry',
            name='communicationslogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='emailuseraction',
            name='emailuser',
        ),
        migrations.RemoveField(
            model_name='emailuseraction',
            name='who',
        ),
        migrations.RemoveField(
            model_name='emailuserlogdocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='emailuserlogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='emailuserlogentry',
            name='emailuser',
        ),
        migrations.AlterField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_addresses', to='address.useraddress'),
        ),
        migrations.AlterField(
            model_name='emailidentity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='billing_same_as_residential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='extra_data',
            field=JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='postal_same_as_residential',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='residential_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='emailuserchangelog',
            name='change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailuserchangelog',
            name='emailuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log_email_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationaddress',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresses', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='metadata',
            field=JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/view/', location='/data/data/projects/feewaiver/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='CommunicationsLogEntry',
        ),
        migrations.DeleteModel(
            name='EmailUserAction',
        ),
        migrations.DeleteModel(
            name='EmailUserLogDocument',
        ),
        migrations.DeleteModel(
            name='EmailUserLogEntry',
        ),
    ]
